require:
  - rubocop-rails
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
AbcSize:
  Exclude:
    - 'db/migrate/*'
MethodLength:
  Exclude:
    - 'db/migrate/*'

