version: '3'
services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3001:3000"
    networks:
      - internal
      - external
    depends_on:
      - db
volumes:
  bundle:
  db:
networks:
  internal:
  external:
    external: true
